DROP TABLE IF EXISTS  STATE_COUNTY_MASTER;
DROP TABLE IF EXISTS COUNTY_RENTAL_PRICES;
DROP TABLE IF EXISTS COUNTY_RENTERS_EVICTION_RATE;
DROP TABLE IF EXISTS COUNTY_DEMOGRAPHICS_AND_INCOME;


CREATE TABLE STATE_COUNTY_MASTER (STATE VARCHAR, 
								  COUNTY VARCHAR,
								  PRIMARY KEY (STATE, COUNTY));
								 
CREATE TABLE COUNTY_ZILLOW_RENTAL_PRICES (ID SERIAL PRIMAY KEY, 
										 STATE VARCHAR,
										 COUNTY VARCHAR,
										 DATE_RECORDED DATE, 
										 AVG_RENT INT,
										 CONSTRAINT STATE_COUNTY 
										  FOREIGN KEY (STATE, COUNTY)
										  REFERENCES STATE_COUNTY_MASTER (STATE, COUNTY))
								 
								 

								 
