DROP TABLE IF EXISTS STATE_COUNTY_MASTER CASCADE;
DROP TABLE IF EXISTS COUNTY_RENTAL_PRICES CASCADE;
DROP TABLE IF EXISTS COUNTY_RENTERS_EVICTIONS CASCADE;
DROP TABLE IF EXISTS COUNTY_DEMOGRAPHICS_AND_INCOME CASCADE;
DROP TABLE IF EXISTS COUNTY_ZILLOW_RENTAL_PRICES CASCADE;


-- DROP THE TABLE IF THEY EXISTS IN THE DATABASE
DROP TABLE IF EXISTS COUNTY_ZILLOW_RENTAL_PRICES CASCADE;
DROP TABLE IF EXISTS COUNTY_DEMOGRAPHICS CASCADE;
DROP TABLE IF EXISTS COUNTY_RENTERS_EVICTIONS CASCADE; 
DROP TABLE IF EXISTS  STATE_COUNTY_MASTER;

--TABLE WILL STORE ALL THE COUNTIES BY STATE IN THE UNITED STATES
CREATE TABLE STATE_COUNTY_MASTER (STATE VARCHAR, 
								  COUNTY VARCHAR,
								  PRIMARY KEY (STATE, COUNTY));
                  
CREATE TABLE COUNTY_ZILLOW_RENTAL_PRICES (ID SERIAL PRIMARY KEY, 
										 STATE VARCHAR,
										 COUNTY VARCHAR,
										 DATE_RECORDED DATE, 
										 AVG_RENT INT);

										 --CONSTRAINT STATE_COUNTY 
										 --FOREIGN KEY (STATE, COUNTY)
										 --REFERENCES STATE_COUNTY_MASTER (STATE, COUNTY));
								 
--TABLE WILL STORE THE DEMOGRAPHICS AND MEDIAN INCOME FOR EACH COUNTY
CREATE TABLE COUNTY_DEMOGRAPHICS_AND_INCOME (ID SERIAL PRIMARY KEY,
										 STATE VARCHAR,
										 COUNTY VARCHAR,
										 YEAR_RECORDED SMALLINT,

										 POPULATION INT,
								  		 POVERTY_RATE_PCT DECIMAL,
								         MEDIAN_HOUSEHOLD_INCOME INT,
								   		 WHITE_PCT DECIMAL,
									     AF_AM_PCT DECIMAL,
									     HISPANIC_PCT DECIMAL,
									     AM_IND_PCT DECIMAL,
								  		 ASIAN_PCT DECIMAL,
								  		 HAWAIIN_PAC_ISL_PCT DECIMAL,
								  		 MULTIPLE_RACE_PCT DECIMAL,
								   		 OTHER_RACES_PCT DECIMAL,	
										 CONSTRAINT STATE_COUNTY_3
										 FOREIGN KEY (STATE, COUNTY)
										 REFERENCES STATE_COUNTY_MASTER (STATE, COUNTY));	
										 
--TABLE WILL STORE THE AVERAGE RENTAL PRICE FOR EACH COUNTY AS RECORDED BY ZILLOW
CREATE TABLE COUNTY_RENTERS_EVICTIONS (ID SERIAL PRIMARY KEY,
										 STATE VARCHAR,
										 COUNTY VARCHAR,
										 YEAR_RECORDED SMALLINT,
								  		 NUMBER_OF_RENTER_HOUSEHOLDS INT,
								  		 RENTER_OCCUPIED_PCT DECIMAL,
								         MEDIAN_GROSS_RENT INT,
								         MEDIAN_PROPERTY_VALUE INT,
									     RENT_BURDEN DECIMAL,
									   	 EVICTION_FILINGS INT,
									   	 ACTUAL_EVICTIONS INT,
									   	 EVICTION_RATE DECIMAL,
									     EVICTION_FILING_RATE DECIMAL,
										 CONSTRAINT STATE_COUNTY_3
										 FOREIGN KEY (STATE, COUNTY)
										 REFERENCES STATE_COUNTY_MASTER (STATE, COUNTY));
